### ISSUE TITLE
doculect names that appear in edictor

### ISSUE THREAD

**Issue by hannalotte** [lessersunda/lexirumah-data#6]
1.  Somehow, the language names appearing in edictor do not 100% match with those in languages.tsv
Example:
In languages.tsv we have 
- Kedang
- Kedang-Lèuwayang
- Kedang- Leubatang
![afbeelding](https://cloud.githubusercontent.com/assets/22792492/25907842/dfb8e524-35a8-11e7-99e0-de4acd8efb93.png)

In Edictor we have:
- Kedang
- Kedang
- Kedang-Lèuwayang
![afbeelding](https://cloud.githubusercontent.com/assets/22792492/25907787/ba7a0d88-35a8-11e7-9b5b-2a95f25bb618.png)

The second Kedang probabaly corresponds to Kedang-Leubatang. 

2. For me personally, it is a pity that I cannot see the end of the language name (which tells me were exactly the data comes from) when I use edictor, especially in the cognate set view. Could we do something about that?? I guess putting the language name earlier woudl destroy again the geographic ordering of the languages .... So, I am not sure.

![afbeelding](https://cloud.githubusercontent.com/assets/22792492/25907686/6ced3f4a-35a8-11e7-8a2f-b93fe1e77ad3.png)

**Comment by hannalotte** [comment]
I have seen changes in the appearance of the language names in the tap-aligned.tsv when using edictor and I really like them! Makes my work much easier. However, two remarks/requests:

- I think the Keraf lists have gone missing now.
- For me to easily get to my selection of languages I work on for the reconstruction, it would still be nice to have a common code after the language name that tells that it belongs to my PEF selection. If that's easy to do, I can tell you on which languages, I would like to have it.

**Comment by Anaphory** [comment]
- [ ] Yes, I rewrote some things, and the PEF tag has suffered from it. That's something I wanted to fix for you.

 - [ ] But that the Keraf lists have disappeared was neither intention nor expected, I'll hunt them down.

**Comment by hannalotte** [comment]
My current preferred selection to reconstruct Proto Eastern Flores would be the following:

- Sika-Maumere
- Sika-Tana Ai
- Hewa
- Lamaholot-Lewoingu
- Lamaholot-Adonara
- Lamaholot-Kalikasa
- Lamaholot-Lerek
- Lamaholot-Lamatuka
- Lamaholot-Lewoeleng
- Kedang-Leubatang
- Kedang-Leuwayang
- Kedang

**Comment by Anaphory** [comment]
I believe the current checkout script generates reasonable names. I need to check whether they need to be made more useful.

**Comment by hannalotte** [comment]
Yeas, actually it's okay how it is now, I think. So, no need for changes from my side for now.
